package com.cn.speedchat.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER_ENTITY.
 */
public class UserEntity {

    private Long id;
    /** Not-null value. */
    private String name;
    private int age;
    private boolean sex;
    /** Not-null value. */
    private String time;

    public UserEntity() {
    }

    public UserEntity(Long id) {
        this.id = id;
    }

    public UserEntity(Long id, String name, int age, boolean sex, String time) {
        this.id = id;
        this.name = name;
        this.age = age;
        this.sex = sex;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public boolean getSex() {
        return sex;
    }

    public void setSex(boolean sex) {
        this.sex = sex;
    }

    /** Not-null value. */
    public String getTime() {
        return time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTime(String time) {
        this.time = time;
    }

	@Override
	public String toString() {
		return "UserEntity [id=" + id + ", name=" + name + ", age=" + age
				+ ", sex=" + sex + ", time=" + time + "]";
	}
    
}
