package com.cekj.didimain.db.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.cekj.didimain.db.greendao.CallEntity;

import com.cekj.didimain.db.greendao.CallEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig callEntityDaoConfig;

    private final CallEntityDao callEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        callEntityDaoConfig = daoConfigMap.get(CallEntityDao.class).clone();
        callEntityDaoConfig.initIdentityScope(type);

        callEntityDao = new CallEntityDao(callEntityDaoConfig, this);

        registerDao(CallEntity.class, callEntityDao);
    }
    
    public void clear() {
        callEntityDaoConfig.getIdentityScope().clear();
    }

    public CallEntityDao getCallEntityDao() {
        return callEntityDao;
    }

}
